name: "[Test] Mobile App"

on:
  push:
    branches:
      - main
      - develop
      - release
      - hotfix
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detox-tests-ios:
    name: "Ledger Live Mobile - iOS Detox Tests"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.push.head.sha }}
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"
      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils
      - name: bump npm
        run: npm i -g npm@8.12.2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: install dependencies
        run: pnpm i --filter="live-mobile..." --filter="ledger-live" --no-frozen-lockfile --unsafe-perm
      - name: Build dependencies
        run: pnpm build:llm:deps
      - name: Build iOS app for Detox test run
        run: pnpm mobile e2e:build -c ios.sim.release
      - name: Test iOS app
        run: pnpm mobile e2e:test -c ios.sim.release --loglevel verbose --record-logs failing --record-timeline all --take-screenshots all --record-videos failing --detectOpenHandles
      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-ios-artifacts
          path: artifacts

  detox-tests-android:
    name: "Ledger Live Mobile - Android Detox Tests"
    runs-on: macos-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=7168"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"
      - name: bump npm
        run: npm i -g npm@8.12.2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
        env:
          ImageOS: ubuntu20
      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: setup Android SDK
        uses: android-actions/setup-android@v2.0.6
      - name: Install dependencies
        run: pnpm i --filter="live-mobile..." --filter="ledger-live" --no-frozen-lockfile --unsafe-perm
      - name: Build dependencies
        run: pnpm build:llm:deps

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-30
      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Build Android app for Detox test run
        run: pnpm mobile e2e:build -c android.emu.release
      - name: Run Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          avd-name: Nexus_6_API_30
          emulator-options: -verbose -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          ram-size: 2048
          script: |
            pnpm mobile e2e:test -c android.emu.release --loglevel verbose --record-logs failing --record-timeline all --take-screenshots all --record-videos failing --detectOpenHandles
      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-android-artifacts
          path: artifacts
